on:
  push:
    branches:
      - main
  workflow_dispatch:
    
env:
  USER_MANAGEMENT_URL: http://localhost:4000
  TODOLIST_BACKEND_URL: http://localhost:8080
  WEBSITE_URL: http://localhost:3000
  SERVER_URL: http://localhost:4000
  SEND_VERIFICATION_EMAIL_URL: "127.0.0.1"
  SMTP_PORT: 3005
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  SMTP_MAIL: ${{ secrets.SMTP_MAIL }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ENV_FILE
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Start MongoDB 6.0
        uses: supercharge/mongodb-github-action@1.9.0

      - name: Checkout the user_management repo
        uses: actions/checkout@v3
        with:
          repository: Scrice994/NextJSTodolistUserManagement
          path: user_management

      - name: Checkout backend repo
        uses: actions/checkout@v3
        with:
          repository: Scrice994/NextJSTodolistBackend
          path: backend
      
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: frontend

      - name: Install user_management dependencies
        working-directory: ./user_management
        run:  npm ci

      - name: Build user_management 
        working-directory: ./user_management
        run:  npm run build

      - name: Start SMTP server
        working-directory: ./user_management
        run:  npm run start:mock &

      - name: Start user_management server
        working-directory: ./user_management
        env:
          PORT: 4000
        run:  npm start &

      - name: install bff dependencies
        working-directory: ./backend
        run: npm ci
      
      - name: build bff
        working-directory: ./backend
        run: npm run build
      
      - name: start bff server
        working-directory: ./backend
        env:
          PORT: 8080
        run: npm start &

      - name: install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: frontend tests
        working-directory: ./frontend
        run: npm run test:api
      

        